name: plant_disease_detector
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  tflite_v2: ^1.0.0
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/model/